# See https://docs.gitlab.com/ce/ci/yaml/README.html for the documentation
image: docker/compose:alpine-1.28.2

variables: &variables
  FF_NETWORK_PER_BUILD: 1
  TANGO_HOST: tango_databaseds:10000

services:
  - name: tangocs/mysql:9.2.2
    alias: tango_mysql
    entrypoint:
      - env
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_INITDB_SKIP_TZINFO=1
      - /usr/local/bin/docker-entrypoint.sh
    command:
      - mysqld
      - --sql-mode=
      - --innodb=OFF
      - --default-storage-engine=MyISAM
  - name: tangocs/tango-cs:9
    alias: tango_databaseds
    entrypoint:
      - env
      - MYSQL_HOST=tango_mysql:3306
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - MYSQL_DATABASE=tango
      - /usr/local/bin/wait-for-it.sh
      - tango_mysql:3306
      - --timeout=30
      - --strict
      - --
    command:
      - /usr/bin/supervisord
      - -c
      - /etc/supervisord.conf

stages:
  - test
  - verify
  - deploy


.job-template: &job-template
  script:
    - mvn clean install
  artifacts:
    paths:
      - assembly/target/*.jar

test-java11:
  image: maven:3.6.3-openjdk-11-slim
  stage: test
  <<: *job-template
  variables:
    <<: *variables

test-java8:
  image: maven:3.6-jdk-8-slim
  stage: test
  <<: *job-template
  variables:
    <<: *variables


#deploy-to-sonar:
#  image: maven:3.6.3-openjdk-11-slim
#  stage: verify
#  script:
#    - mvn clean verify sonar:sonar -Ptravis

# TODO rewrite to gitlab
#  addons:
#    sonarcloud:
#      organization: "tango-controls"
#      token: ${SONAR_TOKEN}

#deploy-to-codacy:
#  image: maven:3.6-jdk-8-slim
#  stage: verify
#  script:
#    - mavn clean install -Ptravis
#    - mvn com.gavinmogan:codacy-maven-plugin:coverage -Ptravis

#deploy-to-codcov:
#  image: maven:3.6-jdk-8-slim
#  stage: verify
#  script:
#    - mvn clean install -Ptravis
#    - bash <(curl -s https://codecov.io/bash)

#deploy-artifacts:
#  image: maven:3.6-jdk-8-slim
#  before_script:
#    - cd parent
#    - mvn versions:set versions:update-child-modules -DnewVersion=${TRAVIS_BRANCH} -DprocessAllModule -DgenerateBackupPoms=false -Prelease
#    - cd ..
#    - mvn install -Dmaven.test.skip=true
#  script:
#    - set -e
#    - .travis/maven_deploy.sh

# TODO rewrite to gitlab
#deploy:
#  - provider: script
#    script: bash .travis/maven_deploy.sh
#    skip_cleanup: true
#    on:
#      tags: true
#  - provider: releases
#    file: assembly/target/JTango-${TRAVIS_TAG}.jar
#    api_key: $GITHUB_TOKEN
#    skip_cleanup: true
#    draft: true
#    on:
#      tags: true